name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'OK to test') }}
    strategy:
      matrix:
        label:
          - ubuntu-latest
          - macos-latest
          - magic_arm64_8core
    runs-on: ${{ matrix.label }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.37.0

      - name: Build packages
        shell: bash
        run: pixi run build-all --channel https://prefix.dev/modular-public-test --channel https://conda.modular.com/max
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
          RATTLER_BUILD_COLOR: always
